"""Script to create and execute live test campaign for US Mental Health."""
import os
import sys
import time

# Ensure UTF-8 console output
if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

# Ensure project root in sys.path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from db.repositories.campaigns_repo import CampaignsRepository
from db.repositories.journalists_repo import JournalistsRepository
from core.matching import JournalistMatcher
from services.ai.orchestrator import AIPitchOrchestrator
from services.ai.openai_service import OpenAIService


def create_and_test_mental_health_campaign():
    c_repo = CampaignsRepository()
    j_repo = JournalistsRepository()
    matcher = JournalistMatcher(j_repo)
    orchestrator = AIPitchOrchestrator()
    ai_service = OpenAIService()

    print("=" * 70)
    print("🧠 CREATING LIVE PR CAMPAIGN: US MENTAL HEALTH INITIATIVE")
    print("=" * 70)

    campaign_data = {
        "name": "2026 US Youth & Workplace Mental Health Crisis Report",
        "story": (
            "A landmark nationwide study across 50 US states reveals a 34% surge in youth anxiety "
            "and severe workplace burnout in 2026, with over 68% of young professionals reporting "
            "inadequate access to clinical therapy. In response, a coalition of mental health researchers "
            "and digital health leaders is unveiling a zero-cost, 24/7 AI-triaged crisis support network "
            "and evidence-based policy toolkit designed to bridge the behavioral healthcare gap nationwide."
        ),
        "target_beat": ["Mental Health", "Public Health", "Health & Addiction", "Healthcare", "Public Policy", "Science"],
        "target_outlets": ["The Wall Street Journal", "CNBC", "Bloomberg", "New York Times", "Forbes", "STAT News"],
        "status": "active",
    }

    # Save campaign to database
    created_campaign = c_repo.create(campaign_data)
    print(f"✅ Campaign created successfully!")
    print(f"   • Campaign ID:   {created_campaign['id']}")
    print(f"   • Campaign Name: {created_campaign['name']}")
    print(f"   • Target Beats:  {', '.join(created_campaign['target_beat'])}")
    print(f"   • Status:        {created_campaign.get('status')}")

    # Rank & Match Journalists from Database (308 journalists)
    print("\n" + "=" * 70)
    print("🎯 RUNNING OPENCLAW 4D + SEMANTIC MATCHING FOR JOURNALISTS")
    print("=" * 70)
    
    # Generate query embedding for campaign
    query_text = f"{campaign_data['name']} {campaign_data['story']} {' '.join(campaign_data['target_beat'])}"
    emb = ai_service.generate_embedding(query_text)
    
    matches = matcher.rank_journalists_for_campaign(created_campaign, query_embedding=emb, top_k=5)
    print(f"Found {len(matches)} Top Matched Journalists:\n")

    for idx, m in enumerate(matches):
        print(f"[{idx + 1}] {m.get('name')} — {m.get('outlet')}")
        print(f"    • Email: {m.get('email')}")
        print(f"    • Beats: {', '.join(m.get('beat') or [])}")
        print(f"    • Match Score: {m.get('match_percentage')}% | 4D Score: {m.get('overall_score', 0):.2f}")

    # Generate Personalized AI Pitches with Xiaomi MiMo
    print("\n" + "=" * 70)
    print("🤖 GENERATING LIVE PITCH WITH XIAOMI MIMO (mimo-v2.5-pro)")
    print("=" * 70)

    top_journalist = matches[0] if matches else {
        "name": "Liz Essley Whyte",
        "outlet": "The Wall Street Journal",
        "beat": ["Mental Health", "Healthcare", "Public Policy"],
        "bio": "Investigative health reporter at WSJ."
    }

    print(f"Generating personalized pitch for: {top_journalist.get('name')} ({top_journalist.get('outlet')})...")
    start = time.time()
    pitch_res = orchestrator.generate_pitch(
        journalist=top_journalist,
        campaign=created_campaign,
        model="mimo-v2.5-pro",
        pitch_type="initial"
    )
    elapsed = time.time() - start
    print(f"✅ Generated by Xiaomi MiMo in {elapsed:.2f}s!\n")
    print("----------------------------------------------------------------------")
    print(f"📌 SUBJECT LINE:\n{pitch_res.get('subject_line')}\n")
    print(f"📝 PITCH EMAIL BODY:\n{pitch_res.get('pitch_email')}")
    print("----------------------------------------------------------------------")

    # Generate Follow-up 1 (Day 3)
    print("\n" + "=" * 70)
    print("⏰ GENERATING FOLLOW-UP 1 (DAY 3 BUMP)")
    print("=" * 70)
    start = time.time()
    followup_res = orchestrator.generate_pitch(
        journalist=top_journalist,
        campaign=created_campaign,
        model="mimo-v2.5-pro",
        pitch_type="followup_1"
    )
    elapsed = time.time() - start
    print(f"✅ Generated Follow-up in {elapsed:.2f}s!\n")
    print(f"📌 FOLLOW-UP SUBJECT: {followup_res.get('subject_line')}\n")
    print(f"📝 FOLLOW-UP BODY:\n{followup_res.get('pitch_email')}")
    print("----------------------------------------------------------------------")

    return created_campaign


if __name__ == "__main__":
    create_and_test_mental_health_campaign()
